- ros_topic_name: "/modimoop/imu/data"
  gz_topic_name: "/model/MODIMOOP/link/imu_link/sensor/imu_sensor/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/modimoop/gps/fix"
  gz_topic_name: "/model/MODIMOOP/link/hull/sensor/gps_sensor/gps"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "gz.msgs.NavSat"
  direction: GZ_TO_ROS

- ros_topic_name: "/modimoop/mag"
  gz_topic_name: "/model/MODIMOOP/link/hull/sensor/mag_sensor/mag"
  ros_type_name: "sensor_msgs/msg/MagneticField"
  gz_type_name: "gz.msgs.Magnetometer"
  direction: GZ_TO_ROS

- ros_topic_name: "/modimoop/joint_states"
  gz_topic_name: "/model/MODIMOOP/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"   # OR gz.msgs.Joint, etc. depends on what it actually is
  direction: GZ_TO_ROS

- ros_topic_name: "/modimoop/anemometer"
  gz_topic_name: "/anemometer"
  ros_type_name: "geometry_msgs/msg/Vector3"
  gz_type_name: "gz.msgs.Vector3d"
  direction: GZ_TO_ROS